# Generated by Django 2.1.4 on 2019-04-27 17:39

from django.db import migrations, models
import student.validation


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.FileField(upload_to='Documents/%Y/%m/%d', validators=[student.validation.validate_file_extension]),
        ),
    ]
